import AppToolboxImplementation from "./AppToolboxImplementation"

export default async (appToolbox: AppToolboxImplementation) => {
  appToolbox.createBackup()
  const zshrcContent = await appToolbox.readZshrc()
  const header = '# GENERATED BY ALIASES CLI'
  const content = 'source $HOME/.aliases'
  !zshrcContent.includes(header) && appToolbox.appendToZshrc(`\n${header}`)
  !zshrcContent.includes(content) && appToolbox.appendToZshrc(`\n${content}\n`)

  // try {
  // } catch (error) {
  //   error instanceof Error && appToolbox.error(error.message)
  // }

}
