import AppToolboxImplementation from "./AppToolboxImplementation"
import { ALIASES_PATH, ZSHRC_PATH } from "./envs"

export default async (appToolbox: AppToolboxImplementation) => {
  !!appToolbox.fileExists(ZSHRC_PATH) && appToolbox.createZshrcBackup()
  !!appToolbox.fileExists(ALIASES_PATH) && appToolbox.createAliasesBackup()

  const zshrcContent = await appToolbox.readZshrc()
  const header = '# GENERATED BY ALIASES CLI'
  const fn = 'reload_aliases() { source ~/.aliases }'
  const src = 'source $HOME/.aliases'
  !zshrcContent?.includes(header) && appToolbox.appendToZshrc(`\n${header}`)
  !zshrcContent?.includes(fn) && appToolbox.appendToZshrc(`\n${fn}`)
  !zshrcContent?.includes(src) && appToolbox.appendToZshrc(`\n${src}\n`)

  appToolbox.appendToAliases('')
}
