import { filesystem } from "gluegun"
import { NOW } from "../../src/utils/envs"
import { waitFor } from "../waitFor"


jest.mock('../../src/utils/envs', () => ({
  ...(jest.requireActual('../../src/utils/envs') as object),
  ZSHRC_PATH: './tmp/zshrc',
  BKP_DIR: './tmp/bkp_dir'
}))

describe('zshrc-prepare', () => {
  test('create backup', async () => {
    filesystem.remove('./tmp')
    filesystem.append('./tmp/zshrc', '#generated for test')
    require('../../src/cli').run(['node', './bin/aliases', ' '])

    await waitFor(
      () => !!filesystem.read('./tmp/bkp_dir/zshrc_' + NOW) && !!filesystem.read('./tmp/zshrc')
    )
    const bkpContent = filesystem.read('./tmp/bkp_dir/zshrc_' + NOW)
    const zshrcContent = filesystem.read('./tmp/zshrc')

    expect(bkpContent).toContain('#generated for test')
    expect(zshrcContent).toContain('# GENERATED BY ALIASES CLI')
    expect(zshrcContent).toContain('source $HOME/.aliases')
  })
})


